<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerG4ywsp3\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerG4ywsp3/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerG4ywsp3.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerG4ywsp3\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerG4ywsp3\App_KernelProdContainer([
    'container.build_hash' => 'G4ywsp3',
    'container.build_id' => '1cc5b323',
    'container.build_time' => 1599550490,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerG4ywsp3');
