<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHx1EYEn\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHx1EYEn/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHx1EYEn.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHx1EYEn\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHx1EYEn\App_KernelDevDebugContainer([
    'container.build_hash' => 'Hx1EYEn',
    'container.build_id' => '0229885a',
    'container.build_time' => 1604347359,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHx1EYEn');
