<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_wdt']], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    'ajoutFichier' => [[], ['_controller' => 'App\\Controller\\FichierController::ajoutFichier'], [], [['text', '/ajoutFichier']], [], []],
    'app_login' => [[], ['_controller' => 'App\\Controller\\SecurityController::login'], [], [['text', '/login']], [], []],
    'app_logout' => [[], ['_controller' => 'App\\Controller\\SecurityController::logout'], [], [['text', '/logout']], [], []],
    'static' => [[], ['_controller' => 'App\\Controller\\StaticController::index'], [], [['text', '/static']], [], []],
    'inscrire' => [[], ['_controller' => 'App\\Controller\\StaticController::inscrire'], [], [['text', '/inscrire']], [], []],
    'contact' => [[], ['_controller' => 'App\\Controller\\StaticController::contact'], [], [['text', '/contact']], [], []],
    'ajout-theme' => [[], ['_controller' => 'App\\Controller\\ThemeController::ajoutTheme'], [], [['text', '/ajout-theme']], [], []],
    'liste_theme' => [[], ['_controller' => 'App\\Controller\\ThemeController::listeTheme'], [], [['text', '/liste_theme']], [], []],
    'modif_theme' => [['id'], ['_controller' => 'App\\Controller\\ThemeController::modifTheme'], ['id' => '\\d+'], [['variable', '/', '\\d+', 'id', true], ['text', '/modif_theme']], [], []],
    'ajout_utilisateur' => [[], ['_controller' => 'App\\Controller\\UtilisateurController::ajout_utilisateur'], [], [['text', '/ajout_utilisateur']], [], []],
    'liste_utilisateur' => [[], ['_controller' => 'App\\Controller\\UtilisateurController::listeUtilisateur'], [], [['text', '/liste_utilisateur/']], [], []],
    'user_profile' => [['id'], ['_controller' => 'App\\Controller\\UtilisateurController::userprofile'], ['id' => '\\d+'], [['variable', '/', '\\d+', 'id', true], ['text', '/user_profile']], [], []],
    'index' => [[], ['_controller' => 'App\\Controller\\StaticController::index'], [], [['text', '/']], [], []],
];
