<?php

namespace Container8ZQ7xbX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getModifThemeTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\ModifThemeType' shared autowired service.
     *
     * @return \App\Form\ModifThemeType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/ModifThemeType.php';

        return $container->privates['App\\Form\\ModifThemeType'] = new \App\Form\ModifThemeType();
    }
}
