<?php

namespace Container8ZQ7xbX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProfilUtilisateurTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\ProfilUtilisateurType' shared autowired service.
     *
     * @return \App\Form\ProfilUtilisateurType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/ProfilUtilisateurType.php';

        return $container->privates['App\\Form\\ProfilUtilisateurType'] = new \App\Form\ProfilUtilisateurType();
    }
}
